# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [2]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [3]:
# Import torch
import torch

# Create random tensor
random_tensor = torch.rand(7,7)
random_tensor

tensor([[0.1605, 0.4226, 0.4418, 0.5563, 0.1156, 0.6534, 0.0457],
        [0.9565, 0.6218, 0.1081, 0.7268, 0.9828, 0.3192, 0.7635],
        [0.7383, 0.9117, 0.4857, 0.7165, 0.9752, 0.0402, 0.0033],
        [0.2405, 0.9992, 0.7916, 0.4730, 0.9544, 0.8907, 0.5764],
        [0.2723, 0.4588, 0.5090, 0.3704, 0.4777, 0.1458, 0.4119],
        [0.9117, 0.0862, 0.3846, 0.4669, 0.3129, 0.6586, 0.0262],
        [0.9774, 0.8405, 0.0930, 0.3503, 0.4653, 0.1595, 0.9066]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [4]:
# Create another random tensor
random_tensor2 = torch.rand(1,7)
# Perform matrix multiplication
matrix_multiplication = torch.matmul(random_tensor, random_tensor2.T)
matrix_multiplication

tensor([[0.9848],
        [1.7239],
        [1.8363],
        [2.1193],
        [1.2273],
        [1.0964],
        [1.7606]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [5]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
tensor1 = torch.rand(7,7)
tensor2 = torch.rand(1,7)

# Matrix multiply tensors
tensor3 = torch.matmul(tensor1,tensor2.T)
tensor3, tensor3.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [6]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [7]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device in use: {device}")
# Create two random tensors on GPU
tensor1_gpu = torch.rand(2,3).to(device)
tensor2_gpu = torch.rand(2,3).to(device)
tensor1_gpu, tensor2_gpu

Device in use: cpu


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]]),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]]))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [8]:
# Perform matmul on tensor_A and tensor_B
tensor3_gpu = torch.matmul(tensor1_gpu, tensor2_gpu.T)
tensor3_gpu

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]])

### 8. Find the maximum and minimum values of the output of 7.

In [9]:
# Find max
max = torch.max(tensor3_gpu)
# Find min
min = torch.min(tensor3_gpu)

max,min

(tensor(0.5617), tensor(0.3647))

### 9. Find the maximum and minimum index values of the output of 7.

In [10]:
# Find arg max
argmax = torch.argmax(tensor3_gpu)

# Find arg min
argmin = torch.argmin(tensor3_gpu)

argmax,argmin

(tensor(3), tensor(0))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [15]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor_A = torch.rand(1,1,1,10)

# Remove single dimensions
tensor_B = tensor_A.squeeze()

# Print out tensors and their shapes
print(f"Tensor A: {tensor_A}, Shape: {tensor_A.shape} \n Tensor B: {tensor_B}, Shape: {tensor_B.shape}")

Tensor A: tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]), Shape: torch.Size([1, 1, 1, 10]) 
 Tensor B: tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]), Shape: torch.Size([10])
